apiVersion: v1
kind: Service
metadata:
  name: citrix-svc
  labels:
    name: citrix-demo-nodeport-svc
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    run: citrix 
