apiVersion: citrix.com/v1
kind: rewritepolicy
metadata:
  name: blacklisturls3
spec:
  responder-policies:
    - servicenames:
        - citrix-svc
      responder-policy:
        respondwith: 
          http-payload-string: '"HTTP/1.1 401 Access denied"'
        respond-criteria: 'http.req.url.equals_any("blacklistUrls")'
        comment: 'Blacklist certain Urls'
    
        
  patset:
    - name: blacklistUrls 
      values:
        - '/app1'
        - '/app2'
        - '/app3'
