apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: citrix 
  annotations: 
    NETSCALER_HTTP_PORT: "8888"
    NETSCALER_VIP: "10.106.162.35"
spec:
  rules:
  - host:  citrix.org
    http:
      paths:
      - path: /
        backend:
          serviceName: citrix-svc
          servicePort: 80
